# docker-compose up --force-recreate

version: '2'

services:
  mounterest:
    container_name: mounterest
    image: asyrjasalo/mounterest:robocon
    command: --debug
    environment:
      - HOST_UID
      - HOST_GID
    ports:
      - 2525:2525
      - 8273:8273
      - 8274:8274
      - 8080:8080
    stop_signal: SIGKILL

  # in case of network disconnections at RoboCon
  jsonserver:
    image: vimagick/json-server
    container_name: jsonserver
    command: db.json
    ports:
      - 3000:3000
    volumes:
      - ./db.json:/app/db.json
    stop_signal: SIGKILL
